version: "3.8"

services:
  app:
    container_name: origin-group-api
    image: udenis123/origin-group:latest
    ports:
      - "8090:8090"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: origin-group-postgresql
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
